CREATE TABLE IF NOT EXISTS pluginexample_players (
    player_uuid CHAR(36) NOT NULL,
    player_name VARCHAR(16) NOT NULL,
    visits BIGINT UNSIGNED NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (player_uuid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
